### ISSUE TITLE
Draw boundaries on map of found resources

### ISSUE THREAD

**Issue by benjaminleighton** [CSIRO-enviro-informatics/loci-integration-app#9]
When resources are navigated to by find location or find by name or via graph traversal draw boundaries on a map to provide a user with visual feedback about that resource.

**Comment by jyucsiro** [comment]
Once the following issues are resolved, we should be able to dereference the feature geometries via the Loc-I Geometry Data Service to draw these on the map in the webapp.

Dependent issues:
https://github.com/CSIRO-enviro-informatics/asgs-dataset/issues/13
https://github.com/CSIRO-enviro-informatics/gnaf-dataset/issues/11
https://github.com/CSIRO-enviro-informatics/geofabric-dataset/issues/26

**Comment by jyucsiro** [comment]
Started to look into this by pulling in from gds.loci.cat in a feature branch https://github.com/CSIRO-enviro-informatics/loci-integration-app/tree/feat_render-graph-once but should rename this or create another feature branch.

**Comment by jyucsiro** [comment]
this is now implemented in https://explorer-dev.loci.cat/ when feature is selected from search-by-point or search by label results
